# Generated by Django 2.2.5 on 2019-09-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_books_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='books/cover/%Y/%m/%d/'),
        ),
    ]
