# Generated by Django 2.2.5 on 2019-09-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_books_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_cover',
            field=models.ImageField(blank=True, upload_to='books/cover/%Y/%m/%d/'),
        ),
    ]
