# Generated by Django 2.2.5 on 2019-09-19 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_category_category_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='books_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='users_read',
            field=models.ManyToManyField(blank=True, choices=[('read', 'Read'), ('reading', 'Reading'), ('Awaiting', 'Awaiting')], related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
