# Generated by Django 2.2.5 on 2019-09-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190919_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='users_like',
        ),
        migrations.RemoveField(
            model_name='books',
            name='users_read',
        ),
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(upload_to='books/cover/%Y/%m/%d/'),
        ),
    ]
