# Generated by Django 2.2.5 on 2019-09-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190922_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelves', models.CharField(choices=[('read', 'Read'), ('reading', 'Currently Reading'), ('want_to_read', 'Want to Read')], default='want_to_read', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_read', to='book.Books')),
            ],
        ),
    ]
